# Generated by Django 3.2.23 on 2024-01-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_auto_20240110_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='amenity_thumbnails/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial')], default=404, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='project',
            name='amenities',
        ),
        migrations.AddField(
            model_name='project',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='projects', to='construction.Amenity'),
        ),
    ]
