# Generated by Django 3.2.23 on 2024-01-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_auto_20240114_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amenities',
        ),
        migrations.AddField(
            model_name='amenity',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='construction.project'),
        ),
    ]
