# Generated by Django 3.2.23 on 2024-01-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_auto_20240114_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='construction.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='project_specifications', to='construction.Specification'),
        ),
    ]
