# Generated by Django 3.2.23 on 2024-01-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_auto_20240114_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='specifications',
        ),
        migrations.CreateModel(
            name='LocationAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='construction.project')),
            ],
        ),
    ]
