# Generated by Django 3.2.23 on 2024-01-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_auto_20240114_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=404),
            preserve_default=False,
        ),
    ]
