# Generated by Django 3.2.23 on 2024-01-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_locationadvantage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationadvantage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
