# Generated by Django 3.2.23 on 2024-01-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0012_rename_contactsubmission_loandocumentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('author', models.CharField(max_length=100)),
                ('date_published', models.DateField()),
                ('content', models.TextField()),
            ],
        ),
    ]
